<?php
$settings = [
    'title' => 'info_media',

    //Отключить указанные блоки (если используется, то block_enabled уже не обрабатывается)
    'block_disabled' => [
//        'accordion',
//        'box',
//        'button_link',
//        'complex_image_text',
//        'complex_video_text',
//        'component',
//        'contents',
//        'coub',
//        'dump',
//        'files',
//        'gallery',
//        'iblock_elements',
//        'iblock_sections',
////        'image',
//        'instagram',
//        'lists',
//        'medialib_collections',
//        'medialib_elements',
//        'properties',
//        'slideshare',
//        'table',
//        'text',
//        'twitter',
//        'video',
//        'video_gallery',
//        'yandex_map',
//        'my_expert',
//        'my_document',
//        'my_article',
//        'my_question',
//        'my_news',
//        'title',
//        'my_title',
////        'my_complex_example',
//        'my_complex_anecdote',
//        'my_complex_exercise',
//        'my_complex_fragment_image',
//        'my_complex_practice'
    ],

    //Разрешить добавление указанных блоков
    'block_enabled' => [
        'accordion',
        'box',
        'button_link',
        'complex_image_text',
        'complex_video_text',
        'component',
        'contents',
        'coub',
        'dump',
        'files',
        'gallery',
        'iblock_elements',
        'iblock_sections',
        'image',
        'instagram',
        'lists',
        'medialib_collections',
        'medialib_elements',
        'properties',
        'slideshare',
        'table',
        'twitter',
        'video',
        'video_gallery',
        'yandex_map',
        'title',
        'my_text',
        'my_detail_video',
        'my_detail_picture',
        'my_courses_program',
        'my_courses_documents',
        'my_courses_about',
        'my_courses_link',
        'my_hero_media',
        'my_project_video_slider',
    ],


//    //Разрешить добавление указанных сеток
    'layout_enabled' => [
        'text',
        'image',
    ],


];
