<?php
$settings = [
    'title' => 'info_page',

    //Отключить указанные блоки (если используется, то block_enabled уже не обрабатывается)
    'block_disabled' => [
//        'accordion',
//        'box',
//        'button_link',
//        'complex_image_text',
//        'complex_video_text',
//        'component',
//        'contents',
//        'coub',
//        'dump',
//        'files',
//        'gallery',
//        'iblock_elements',
//        'iblock_sections',
////        'image',
//        'instagram',
//        'lists',
//        'medialib_collections',
//        'medialib_elements',
//        'properties',
//        'slideshare',
//        'table',
//        'text',
//        'twitter',
//        'video',
//        'video_gallery',
//        'yandex_map',
//        'my_expert',
//        'my_document',
//        'my_article',
//        'my_question',
//        'my_news',
//        'title',
//        'my_title',
////        'my_complex_example',
//        'my_complex_anecdote',
//        'my_complex_exercise',
//        'my_complex_fragment_image',
//        'my_complex_practice'
    ],

    //Разрешить добавление указанных блоков
    'block_enabled' => [
        'accordion',
        'box',
        'button_link',
        'complex_image_text',
        'complex_video_text',
        'component',
        'contents',
        'coub',
        'dump',
        'files',
        'gallery',
        'iblock_elements',
        'iblock_sections',
        'image',
        'instagram',
        'lists',
        'medialib_collections',
        'medialib_elements',
        'properties',
        'slideshare',
        'table',
        'text',
        'twitter',
        'video',
        'video_gallery',
        'yandex_map',
        'title',
        'my_about_intro',
        'my_about_hero',
        'my_about_guide',
        'my_about_why',
        'my_about_statistic',
        'my_about_acting',
        'my_about_group',
        'my_about_solutions',
        'my_about_cases_text',
        'my_about_partner',
        'my_about_cases',
        'my_about_partners_intro',
        'my_about_partners_cases',
        'my_page_intro',
        'my_contributors',
        'my_solutions',
        'my_main_hero_text',
        'my_main_section1',
        'my_main_section2',
        'my_main_section3',
        'my_main_section4',
        'my_main_section5',
        'my_main_partners',
        'my_cases',
        'my_divein_intro',
        'my_divein_events',
        'my_divein_blog',
        'my_divein_program',
        'my_divein_test',
        'my_divein_insights',
        'my_divein_image_link',
        'my_terms_htag',
        'my_terms_description',
        'my_terms_text',
    ],


//    //Разрешить добавление указанных сеток
    'layout_enabled' => [
        'text',
        'image',
    ],


];
