<?php
$settings = [
    'title' => 'project',

    //Отключить указанные блоки (если используется, то block_enabled уже не обрабатывается)
    'block_disabled' => [
//        'accordion',
//        'box',
//        'button_link',
//        'complex_image_text',
//        'complex_video_text',
//        'component',
//        'contents',
//        'coub',
//        'dump',
//        'files',
//        'gallery',
//        'iblock_elements',
//        'iblock_sections',
////        'image',
//        'instagram',
//        'lists',
//        'medialib_collections',
//        'medialib_elements',
//        'properties',
//        'slideshare',
//        'table',
//        'text',
//        'twitter',
//        'video',
//        'video_gallery',
//        'yandex_map',
//        'my_expert',
//        'my_document',
//        'my_article',
//        'my_question',
//        'my_news',
//        'title',
//        'my_title',
////        'my_complex_example',
//        'my_complex_anecdote',
//        'my_complex_exercise',
//        'my_complex_fragment_image',
//        'my_complex_practice'
    ],

    //Разрешить добавление указанных блоков
    'block_enabled' => [
        'accordion',
        'box',
        'button_link',
        'complex_image_text',
        'complex_video_text',
        'component',
        'contents',
        'coub',
        'dump',
        'files',
        'gallery',
        'iblock_elements',
        'iblock_sections',
        'image',
        'instagram',
        'lists',
        'medialib_collections',
        'medialib_elements',
        'properties',
        'slideshare',
        'table',
        'text',
        'twitter',
        'video',
        'video_gallery',
        'yandex_map',
        'title',
        'my_hero',
        'my_hero_media',
        'my_hero_partner',
        'my_project_goal',
        'my_project_members',
        'my_project_speakers',
        'my_complex_project_result',
        'my_translation',
        'my_project_contacts',
        'my_input',
        'my_project_program',
        'my_other_events',
        'my_video_block',
        'my_project_documents',
        'my_project_cases',
        'my_project_contacts_2',
        'my_project_statistic_new',
        'my_project_features_new',
        'my_project_program_new',
        'my_project_video_slider',
		'my_hero_company',
		'my_html',
        'my_project_focus',
        'my_project_enjoy',
        'my_project_team',
        'my_project_itquote',
        'my_project_itvideo',
        'my_project_future_events',
        'my_project_sharing',
        'my_form',
        'my_poll',
    ],


//    //Разрешить добавление указанных сеток
    'layout_enabled' => [
        'text',
        'image',
    ],


];
