addons:
  ssh_known_hosts: 51.250.7.167

before_deploy:
  - echo "$ssh_key" | base64 -d > /tmp/deploy_key
  - eval "$(ssh-agent -s)"
  - chmod 600 /tmp/deploy_key
  - ssh-add /tmp/deploy_key
 
deploy:
  provider: script
  skip_cleanup: true
  script:
    #- ssh -p $SSH_PORT $SSH_USER@$SSH_HOST "cd $DOC_ROOT && git reset --hard HEAD"
    - ssh -p $SSH_PORT $SSH_USER@$SSH_HOST "cd $DOC_ROOT && git checkout master"
    - ssh -p $SSH_PORT $SSH_USER@$SSH_HOST "cd $DOC_ROOT && git pull origin master"
  on:
    branch: master

